In [3]:
from PIL import Image
from os import listdir
from matplotlib import image
import numpy as np
from numpy import asarray
from matplotlib import pyplot
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import numpy as np
from keras import layers
from keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from keras.models import Model, load_model
#from keras.preprocessing import image
from keras.utils import layer_utils
from keras.utils.data_utils import get_file
from keras.applications.imagenet_utils import preprocess_input
import pydot
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
#from resnets_utils import *
from keras.initializers import glorot_uniform
import scipy.misc
from matplotlib.pyplot import imshow
%matplotlib inline

import keras.backend as K
K.set_image_data_format('channels_last')
K.set_learning_phase(1)

import IPython.display as ipd
import glob
from scipy.io import wavfile
import numpy as np
import pandas as pd
import librosa
import librosa.display
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib as plt
import matplotlib.pyplot as plt
import struct
from scipy.io import wavfile as wav
from scipy.io.wavfile import write
import os
from datetime import datetime 
from sklearn import metrics 
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, Conv2D, MaxPooling2D, GlobalAveragePooling2D
from keras.optimizers import Adam
from keras.utils import np_utils, to_categorical
from keras.callbacks import ModelCheckpoint 

C:\Users\reban\anaconda3\lib\site-packages\tensorflow\python\keras\backend.py:434: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '


In [4]:
# load all images in a directory
n_images=750;
length=64;
width=64;
class_num=40
i=0;
list_imgs=np.zeros((n_images,length,width,3))
loaded_images = list()
for filename in listdir('Executable_Uclass'):
    # load image
    img_data = image.imread('Executable_Uclass/' + filename)
    im = Image.open('Executable_Uclass/' + filename)
    new_image = im.resize((length, width))
    np_im = np.array(new_image)
    #pyplot.imshow(np_im)
    #pyplot.show()
    list_imgs[i,:,:,:] = np.array(np_im);
    loaded_images.append(filename)
    #print('> loaded %s %s' % (filename, np_im.shape))
    i=i+1;
print(i);

750


In [10]:
def identity_block(X, f, filters, stage, block):
    """
    Implementation of the identity block as defined in Figure 3
    
    Arguments:
    X -- input tensor of shape (m, n_H_prev, n_W_prev, n_C_prev)
    f -- integer, specifying the shape of the middle CONV's window for the main path
    filters -- python list of integers, defining the number of filters in the CONV layers of the main path
    stage -- integer, used to name the layers, depending on their position in the network

    block -- string/character, used to name the layers, depending on their position in the network
    
    Returns:
    X -- output of the identity block, tensor of shape (n_H, n_W, n_C)
    """
    
    # defining name basis
    conv_name_base = 'res' + str(stage) + block + '_branch'
    bn_name_base = 'bn' + str(stage) + block + '_branch'
    
    # Retrieve Filters
    F1, F2, F3 = filters
    
    # Save the input value. You'll need this later to add back to the main path. 
    X_shortcut = X
    
    # First component of main path
    X = Conv2D(filters = F1, kernel_size = (1, 1), strides = (1,1), padding = 'valid', name = conv_name_base + '2a', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2a')(X)
    X = Activation('relu')(X)

    
    # Second component of main path (≈3 lines)
    X = Conv2D(filters = F2, kernel_size = (f, f), strides = (1,1), padding = 'same', name = conv_name_base + '2b', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2b')(X)
    X = Activation('relu')(X)

    # Third component of main path (≈2 lines)
    X = Conv2D(filters = F3, kernel_size = (1, 1), strides = (1,1), padding = 'valid', name = conv_name_base + '2c', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2c')(X)

    # Final step: Add shortcut value to main path, and pass it through a RELU activation (≈2 lines)
    X = Add()([X, X_shortcut])
    X = Activation('relu')(X)
    
    
    return X

In [11]:
def convolutional_block(X, f, filters, stage, block, s = 2):
    """
    Implementation of the convolutional block as defined in Figure 4
    
    Arguments:
    X -- input tensor of shape (m, n_H_prev, n_W_prev, n_C_prev)
    f -- integer, specifying the shape of the middle CONV's window for the main path
    filters -- python list of integers, defining the number of filters in the CONV layers of the main path
    stage -- integer, used to name the layers, depending on their position in the network
    block -- string/character, used to name the layers, depending on their position in the network
    s -- Integer, specifying the stride to be used
    
    Returns:
    X -- output of the convolutional block, tensor of shape (n_H, n_W, n_C)
    """
    
    # defining name basis
    conv_name_base = 'res' + str(stage) + block + '_branch'
    bn_name_base = 'bn' + str(stage) + block + '_branch'
    
    # Retrieve Filters
    F1, F2, F3 = filters
    
    # Save the input value
    X_shortcut = X


    ##### MAIN PATH #####
    # First component of main path 
    X = Conv2D(F1, (1, 1), strides = (s,s), name = conv_name_base + '2a', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2a')(X)
    X = Activation('relu')(X)

    # Second component of main path (≈3 lines)
    X = Conv2D(filters = F2, kernel_size = (f, f), strides = (1,1), padding = 'same', name = conv_name_base + '2b', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2b')(X)
    X = Activation('relu')(X)
    # Third component of main path (≈2 lines)
    X = Conv2D(filters = F3, kernel_size = (1, 1), strides = (1,1), padding = 'valid', name = conv_name_base + '2c', kernel_initializer = glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis = 3, name = bn_name_base + '2c')(X)


    ##### SHORTCUT PATH #### (≈2 lines)
    X_shortcut = Conv2D(filters = F3, kernel_size = (1, 1), strides = (s,s), padding = 'valid', name = conv_name_base + '1',
                        kernel_initializer = glorot_uniform(seed=0))(X_shortcut)
    X_shortcut = BatchNormalization(axis = 3, name = bn_name_base + '1')(X_shortcut)

    # Final step: Add shortcut value to main path, and pass it through a RELU activation (≈2 lines)
    X = Add()([X, X_shortcut])
    X = Activation('relu')(X)
    
    
    return X

In [12]:
def ResNet50(input_shape=(length, width, 3), classes=class_num):
    """
    Implementation of the popular ResNet50 the following architecture:
    CONV2D -> BATCHNORM -> RELU -> MAXPOOL -> CONVBLOCK -> IDBLOCK*2 -> CONVBLOCK -> IDBLOCK*3
    -> CONVBLOCK -> IDBLOCK*5 -> CONVBLOCK -> IDBLOCK*2 -> AVGPOOL -> TOPLAYER

    Arguments:
    input_shape -- shape of the images of the dataset
    classes -- integer, number of classes

    Returns:
    model -- a Model() instance in Keras
    """

    # Define the input as a tensor with shape input_shape
    X_input = Input(input_shape)

    # Zero-Padding
    X = ZeroPadding2D((3, 3))(X_input)

    # Stage 1
    X = Conv2D(64, (7, 7), strides=(2, 2), name='conv1', kernel_initializer=glorot_uniform(seed=0))(X)
    X = BatchNormalization(axis=3, name='bn_conv1')(X)
    X = Activation('relu')(X)
    X = MaxPooling2D((3, 3), strides=(2, 2))(X)

    # Stage 2
    X = convolutional_block(X, f=3, filters=[64, 64, 256], stage=2, block='a', s=1)
    X = identity_block(X, 3, [64, 64, 256], stage=2, block='b')
    X = identity_block(X, 3, [64, 64, 256], stage=2, block='c')

    ### START CODE HERE ###

    # Stage 3 (≈4 lines)
    X = convolutional_block(X, f = 3, filters = [128, 128, 512], stage = 3, block='a', s = 2)
    X = identity_block(X, 3, [128, 128, 512], stage=3, block='b')
    X = identity_block(X, 3, [128, 128, 512], stage=3, block='c')
    X = identity_block(X, 3, [128, 128, 512], stage=3, block='d')

    # Stage 4 (≈6 lines)
    X = convolutional_block(X, f = 3, filters = [256, 256, 1024], stage = 4, block='a', s = 2)
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='b')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='c')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='d')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='e')
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block='f')

    # Stage 5 (≈3 lines)
    X = convolutional_block(X, f = 3, filters = [512, 512, 2048], stage = 5, block='a', s = 2)
    X = identity_block(X, 3, [512, 512, 2048], stage=5, block='b')
    X = identity_block(X, 3, [512, 512, 2048], stage=5, block='c')

    # AVGPOOL (≈1 line). Use "X = AveragePooling2D(...)(X)"
    X = AveragePooling2D((2,2), name="avg_pool")(X)

    ### END CODE HERE ###

    # output layer
    X = Flatten()(X)
    X = Dense(classes, activation='softmax', name='fc' + str(classes), kernel_initializer = glorot_uniform(seed=0))(X)
    
    
    # Create model
    model = Model(inputs = X_input, outputs = X, name='ResNet50')

    return model

In [14]:
model = ResNet50(input_shape = (length, width, 3), classes = class_num)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "ResNet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 64, 64, 3)]  0                                            
__________________________________________________________________________________________________
zero_padding2d_1 (ZeroPadding2D (None, 70, 70, 3)    0           input_2[0][0]                    
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 32, 32, 64)   9472        zero_padding2d_1[0][0]           
__________________________________________________________________________________________________
bn_conv1 (BatchNormalization)   (None, 32, 32, 64)   256         conv1[0][0]                      
___________________________________________________________________________________________

In [15]:
xx=model(list_imgs)
print(xx)
xx=xx.numpy()

tf.Tensor(
[[0.00938466 0.00234761 0.00391463 ... 0.00285996 0.0085479  0.05113548]
 [0.00709436 0.00330803 0.0125608  ... 0.00087098 0.0018533  0.03492791]
 [0.03265127 0.00289742 0.01015655 ... 0.00118811 0.0009113  0.03982856]
 ...
 [0.02255757 0.00041649 0.00337595 ... 0.00031795 0.00319548 0.01268369]
 [0.0089745  0.0007326  0.00107662 ... 0.00025566 0.00301161 0.00551938]
 [0.00497154 0.00206174 0.00092572 ... 0.00103176 0.00138371 0.00751885]], shape=(750, 40), dtype=float32)


In [16]:
df = pd.DataFrame(xx)
## save to xlsx file
filepath = 'features_Uclass.xlsx'
df.to_excel(filepath, index=False)


In [17]:
df

0         1         2         3         4         5         6   \
0    0.009385  0.002348  0.003915  0.006449  0.004351  0.181685  0.200163   
1    0.007094  0.003308  0.012561  0.010179  0.014103  0.030731  0.091469   
2    0.032651  0.002897  0.010157  0.001635  0.001125  0.018885  0.370287   
3    0.012732  0.002198  0.001309  0.004247  0.002261  0.038423  0.352992   
4    0.019955  0.005963  0.004113  0.005088  0.005687  0.040118  0.132671   
..        ...       ...       ...       ...       ...       ...       ...   
745  0.030150  0.002659  0.001425  0.001211  0.001269  0.089268  0.064077   
746  0.043386  0.000635  0.001792  0.008161  0.006119  0.255374  0.236782   
747  0.022558  0.000416  0.003376  0.005120  0.001124  0.034207  0.092571   
748  0.008974  0.000733  0.001077  0.002741  0.002561  0.083736  0.163019   
749  0.004972  0.002062  0.000926  0.003495  0.004197  0.027433  0.299606   

           7         8         9   ...        30        31        32  \
0    0.021916  0.001918  0.017859  ...  0.000827  0.117364  0.002176   
1    0.028738  0.000705  0.007480  ...  0.000299  0.227549  0.000930   
2    0.021320  0.003260  0.025795  ...  0.001765  0.106391  0.002723   
3    0.024171  0.002381  0.008319  ...  0.000200  0.118814  0.001204   
4    0.017777  0.003234  0.012437  ...  0.000864  0.132159  0.001487   
..        ...       ...       ...  ...       ...       ...       ...   
745  0.015631  0.007665  0.011978  ...  0.000717  0.404319  0.002308   
746  0.018278  0.002175  0.016544  ...  0.000225  0.055377  0.002008   
747  0.018054  0.000761  0.030685  ...  0.000989  0.379888  0.001112   
748  0.039109  0.001793  0.047280  ...  0.000458  0.176810  0.002971   
749  0.030523  0.002453  0.024101  ...  0.001243  0.118515  0.005460   

           33        34        35        36        37        38        39  
0    0.002183  0.050798  0.003888  0.001514  0.002860  0.008548  0.051135  
1    0.006110  0.065865  0.006311  0.002302  0.000871  0.001853  0.034928  
2    0.001133  0.032020  0.004825  0.018164  0.001188  0.000911  0.039829  
3    0.018153  0.049816  0.001901  0.002660  0.000354  0.004175  0.008483  
4    0.002965  0.022782  0.006417  0.003903  0.000420  0.002092  0.072917  
..        ...       ...       ...       ...       ...       ...       ...  
745  0.002398  0.019472  0.001699  0.001602  0.000609  0.000587  0.012748  
746  0.001529  0.034740  0.002875  0.001583  0.000772  0.001217  0.005105  
747  0.004379  0.050736  0.000934  0.006992  0.000318  0.003195  0.012684  
748  0.001385  0.029778  0.005008  0.010090  0.000256  0.003012  0.005519  
749  0.002189  0.012893  0.001485  0.001458  0.001032  0.001384  0.007519  

[750 rows x 40 columns]

In [ ]:
===============================================================================================================================